#!/bin/bash


if [[ "$(uname)" -eq "Darwin" ]]; then
  greadlink 2>&1 /dev/null
  if [[ $? -ne 0 ]]; then
    brew install coreutils
  fi
  SRC=$(dirname $(greadlink -e $0))
else
  SRC=$(dirname $(readlink -e $0))
fi


# vim-plug: Simple plugin manager to download directly from github instead of saving all our plugins locally
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ ! -d "$HOME/.vimrc" ]; then
    ln -s "$SRC/vimrc" "$HOME/.vimrc"
fi
